### ISSUE TITLE
A few observations...

### ISSUE THREAD

**Issue by bonbonio** [hupe1980/gatsby-theme-material-ui#1]
Hi,

I will submit a PR for the missing docs page and maybe with some clearer examples of using a few Material-UI goodies; but I have some general feedback.

### 1. yarn start:*
I also could not make it work with the 

yarn start:*

Instead I ran it with yarn start:www

### 2. The structure of the project does seem odd - is it necessary for the two node_modules folders?

I tried following the Gatsy Material-UI plugin flow but it didnt work for me, so this repository has been far better as it has worked mostly out of the box so thank you.

### 3. The examples need tweaked, currently there are a few component specific styles which made me think the global MUI styles did not work; so i will try to build a nicer default for this repo later if you want?

**Comment by hupe1980** [comment]
@bonbonio 
1. yarn:start:* The asterix is a placeholder. You have to replce it with www | simple | using-redux
2. This repository is a monorepo managed with lerna. It contains several projects with own node_modules folders
3. Better examples are always welcome
