### ISSUE TITLE
Clarification of usage on material ui repo

### ISSUE THREAD

**Issue by valoricDe** [hupe1980/gatsby-theme-material-ui#12]
Hi, on https://www.gatsbyjs.org/packages/gatsby-plugin-material-ui/ it is stated that an example is on the material ui repo (https://github.com/mui-org/material-ui/tree/master/examples/gatsby)
But somehow they do not use this plugin anymore. The approach on material ui tho has no proper ssr style injection. Does someone know why the material ui maintainer abbandoned this plugin?

**Comment by valoricDe** [comment]
#ignore

**Comment by sushilbansal** [comment]
Hi @valoricDe did you find the reason?

**Comment by valoricDe** [comment]
@sushilbansal I used a previously cloned project without making a git pull before writing this issue. The newest version does indeed use `"gatsby-plugin-material-ui": "latest",` https://github.com/mui-org/material-ui/blob/master/examples/gatsby/package.json#L8
