### ISSUE TITLE
TypeScript typings?

### ISSUE THREAD

**Issue by austinbutler** [hupe1980/gatsby-theme-material-ui#13]
I get `Could not find a declaration file for module 'gatsby-theme-material-ui'` when using this in my project, and therefore `Link` for example has no understanding of acceptable props.

Any chance of adding typings?

**Comment by hupe1980** [comment]
@austinbutler You are welcome to create a PR. Do you want to try?

**Comment by ohlr** [comment]
Please reopen

**Comment by oliviertassinari** [comment]
@hupe1980 I would recommend disabling the inactivity bot. So far, from my experience, it doesn't worth it for a project like *gatsby-theme-material-ui* with a relatively low level of issue activity.
