### ISSUE TITLE
Using a non-Google font

### ISSUE THREAD

**Issue by ianjanicki** [hupe1980/gatsby-theme-material-ui#16]
Great package! Thanks for building.

I'm leveraging [a package for Inter](https://www.npmjs.com/package/typeface-inter), since Inter is not currently supported by Google Fonts and it's my desired font.

I'm unsure how to avoid fonts getting pre-loaded by this plugin. I've tried:
```
// gatsby-config.js

{
   resolve: `gatsby-theme-material-ui`,
   options: {
     webFontsConfig: null
     },
   },
}
```

But this breaks the build since Roboto still seems to be added to `index.html`. How can I prevent this?

**Comment by hupe1980** [comment]
I fixed the plugin gatsby-plugin-webfonts. After that, the error should no longer occur

**Comment by ianjanicki** [comment]
Thanks @hupe1980! Is my snippet above the correct way of prevent this behavior going forward?

**Comment by hupe1980** [comment]
Yes, that's right...

```javascript
plugins: [
    {
      resolve: `gatsby-theme-material-ui`,
      options: {
        webFontsConfig: null,
      },
    },
  ],
```

**Comment by panzacoder** [comment]
This seems to cause errors with @mui v5 and the the `latest` of this plugin.

```
 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve '/.cache/webfonts/webfonts.css' in '/Users/jshebert/Development/lightstep-web/node_modules/gatsby-plugin-webfonts'

If you're trying to use a package make sure that '/.cache/webfonts/webfonts.css' is installed. If you're trying to use a local file make sure that the path is
 correct.

File: node_modules/gatsby-plugin-webfonts/gatsby-ssr.js:24:39

not finished Building development bundle - 5.847s
not finished Caching HTML renderer compilation - 0.023s
```
