### ISSUE TITLE
Missing @material-ui/core dependency in install doc

### ISSUE THREAD

**Issue by florent-andre** [hupe1980/gatsby-theme-material-ui#18]
For thus who start with a minimal gatsby intall from scratch like me...
Thanks for the lib, regards.

**Comment by oliviertassinari** [comment]
Do you wish it to be mentioned in https://github.com/hupe1980/gatsby-theme-material-ui/tree/master/packages/gatsby-theme-material-ui#install?

**Comment by florent-andre** [comment]
Yes I think it could be the better place for it !

**Comment by oliviertassinari** [comment]
In this case, I think that you could try a pull request, I belive the author of this package would appreciate it.
