### ISSUE TITLE
Missing Gatsbylink for ListItem

### ISSUE THREAD

**Issue by rejas** [hupe1980/gatsby-theme-material-ui#19]
Would it be possible (and/or the correct way) to adapt the ListItem component of material-ui to use the GatsbyLink too? Or how would one implement a list of lickable items otherwise:

```
          <List>
              <ListItem to={"/my-page-1"}>
                  <ListItemText primary="Click me for page1"/>
              </ListItem>
          </List>
```

**Comment by oliviertassinari** [comment]
Please submit support requests and questions to StackOverflow using the tag [material-ui](http://stackoverflow.com/tags/material-ui). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/callemall/material-ui/blob/master/CONTRIBUTING.md).

**Comment by oliviertassinari** [comment]
Tip: you can find an example in the mui repository.

**Comment by rejas** [comment]
Thx for the tip. Solved it by using this construct (in case someone stumbles across this):

```
import { GatsbyLink } from 'gatsby-theme-material-ui';

...

<ListItem button component={GatsbyLink} to={"/my-page-1"}>
```
