### ISSUE TITLE
Unexpected Token '<'

### ISSUE THREAD

**Issue by BlackFenix2** [hupe1980/gatsby-theme-material-ui#23]
I keep getting this error message when i load the Gatsby-Theme-Material-UI package in my project. 
I do use Typescript for my project but that should not affect how the .js files compile. i did not override any of the gatsby babel settings.

```js
**\node_modules\gatsby-theme-material-ui-top-layout\src\wrap-with-provider.js: Unexpected token (7:9)

  5 | 
  6 | export default function wrapWithProvider({ element }) {
> 7 |   return <TopLayout theme={theme}>{element}</TopLayout>;
    |          ^
  8 | }
  9 | 

File: ..\..\node_modules\gatsby-theme-material-ui-top-layout\src\wrap-with-provider.js:7:9

```

**Comment by BlackFenix2** [comment]
If i move this plugin from my gatsby-theme-core workspace and move it right to my site project, i load up just fine. it appears i cannot add this theme as a plugin to my custom theme in a yarn workspace.

**Comment by topolanekmartin** [comment]
Same here
