### ISSUE TITLE
Use class based components instead of function based components

### ISSUE THREAD

**Issue by ohlr** [hupe1980/gatsby-theme-material-ui#30]
function based components do not accept refs.

In a scenario like this https://material-ui.com/components/menus/#menulist-composition the button needs to hold a ref. If it at the same time requires a link functionality I can not simply use Button from this package because then I am getting a function based component.

**Comment by oliviertassinari** [comment]
React.forwardRef

**Comment by ohlr** [comment]
@oliviertassinari You are right it even says it in the browser consoe:

`index.js:2177 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

```
import { Button } from "gatsby-theme-material-ui";

const anchorRef = React.useRef<HTMLButtonElement>(null);
 <Button ref={anchorRef} > test </Button>
```

**Comment by oliviertassinari** [comment]
Ok, I think that we definitely miss a forwarfRef in 

https://github.com/hupe1980/gatsby-theme-material-ui/blob/cfe266bec4aa4cb651bd60c1f63bb80d07e6463c/packages/gatsby-material-ui-components/src/patch-base-button-components.tsx#L10

**Comment by ohlr** [comment]
@ohlr https://github.com/ohlr/gatsby-mui-theme-bug/blob/master/src/pages/index.js with this you should be able to reproduce.

**Comment by ohlr** [comment]
activity
