### ISSUE TITLE
What is createStore in Customizing?

### ISSUE THREAD

**Issue by dandv** [hupe1980/gatsby-theme-material-ui#34]
For new users who install the theme via NPM, the documentation at https://github.com/hupe1980/gatsby-theme-material-ui/tree/master/packages/gatsby-theme-material-ui#customizing, is unclear on where `createStore` is supposed to come from.

Maybe the example was copied from [the redux one](https://github.com/hupe1980/gatsby-theme-material-ui/blob/master/examples/using-redux/src/gatsby-theme-material-ui-top-layout/components/top-layout.js)?

**Comment by hupe1980** [comment]
Yes exactly. This is an excerpt from the Redux example
